### ISSUE TITLE
how to send icp to an account

### ISSUE THREAD

**Issue by xiao11lang** [AstroxNetwork/agent_dart#11]
I want to send icp to account: 1586275a55430abba47862989da56f2c9ac31bc9f1c58739d6637a33714f307a
Here is my code:
    var mne ='xxx';
    var p = RosettaApi();
    var key = fromMnemonicWithoutValidation(mne, []);
    await p.init();
    var pre = await p.transferPreCombine(
        key.getPublicKey().toRaw(),
        hex.HEX.decode(
            '1586275a55430abba47862989da56f2c9ac31bc9f1c58739d6637a33714f307a'),
        BigInt.from(90000),
        BigInt.from(10000),
        {});
    var s = await transferCombine(key, pre);
    var res = await p.transfer_post_combine(s);
    print(res);

But when I run code above, I get some error. Could you please give me a code example, thanks.

**Comment by neeboo** [comment]
In a day or two. Hang tight
2021年10月9日 +0800 PM4:00 xiao11lang ***@***.***>，写道：

**Comment by xiao11lang** [comment]
> In a day or two. Hang tight 2021年10月9日 +0800 PM4:00 xiao11lang ***@***.***>，写道：
> […](#)
> I want to send icp to account: 1586275a55430abba47862989da56f2c9ac31bc9f1c58739d6637a33714f307a Here is my code: var mne ='xxx'; var p = RosettaApi(); var key = fromMnemonicWithoutValidation(mne, []); await p.init(); var pre = await p.transferPreCombine( key.getPublicKey().toRaw(), hex.HEX.decode( '1586275a55430abba47862989da56f2c9ac31bc9f1c58739d6637a33714f307a'), BigInt.from(90000), BigInt.from(10000), {}); var s = await transferCombine(key, pre); var res = await p.transfer_post_combine(s); print(res); But when I run code above, I get some error. Could you please give me a code example, thanks. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
Thanks for reply. I found that there may be errors in the source code.  When use transferCombine , I got a error. I think it may be the problem of the combine function.  The wrong statement is:
var update = unsignedTransaction["updates"][0];
Should it be :
var update = unsignedTransaction["updates"][0][1];
After I changed source code and send message, I got error: Cannot deserialize the submit request in CBOR format because of: invalid type: map, expected variant identifier. How do I solve this
