### ISSUE TITLE
[Bounty] Candid builder for dart class

### ISSUE THREAD

**Issue by neeboo** [AstroxNetwork/agent_dart#12]
# Description
To build a candid builder for agent dart

## Context
Candid is used to describe IDL for canister functions.
Candid builder is used to transform candid files to usable functions/classes for agent clients in different languages.
For dart language, all interfaces are classes. To make a workable builder, like we do json decoding classes, candid builder should also transform all those interfaces into classes.

Candid files are trans-compiled into typescript and javascript using `didc`, link is [here](https://github.com/dfinity/candid/tree/master/tools/didc)

There are repos maintained by community for other languages:
1.  [Kotlin](https://github.com/seniorjoinu/candid-kt)
2. [Haskell](https://github.com/nomeata/haskell-candid)
3. [AssemblyScript](https://github.com/rckprtr/cdk-as/tree/master/packages/cdk/assembly/candid)
4. [elm](https://github.com/chenyan2002/ic-elm/)

Since agent_dart is ported agains `agent-js`, all IDL interfaces and styles are very similar to javascript/typescript.

for example , in generarted javascript:
```javascript
const Purpose = IDL.Variant({
    'authentication' : IDL.Null,
    'recovery' : IDL.Null,
});
const CredentialId = IDL.Vec(IDL.Nat8);
```
in agent_dart, we can almost simply copy paste
```dart
final Purpose = IDL.Variant({
    'authentication' : IDL.Null,
    'recovery' : IDL.Null,
});
final CredentialId = IDL.Vec(IDL.Nat8);
```

So we might be able to :
1. modify and use `didc` to generate those `idl`, 
2. THEN write classes using dart builder

To see working classes in dart, please refer to [wallet/ledger.dart](https://github.com/AstroxNetwork/agent_dart/blob/main/lib/wallet/ledger.dart)

# Acceptance Criteria
* [ ] modify and combine `didc` to builder to generate `idl`s
* [ ] use dart builder to generate artifacts in dart classes
* [ ] tests and working examples, published to other repo.

# Reward
30 ICPs

**Comment by zbyzhlsp** [comment]
i'll deal with it @neeboo

**Comment by neeboo** [comment]
> i'll deal with it @neeboo

cool, let's discuss it

**Comment by neeboo** [comment]
According discussion, please update targets ETA:

 1. modify and combine didc to builder to generate idls
 
     ETA:
 2. use dart builder to generate artifacts in dart classes
     
    ETA:

 3. tests and working examples, published to other repo.
     
    ETA:

**Comment by zbyzhlsp** [comment]
hi @neeboo ,I'm tring to make a didc demo with dart support（just a very simple demo to check my idea）,here's what I have done:
1. Add  dart support for subcommand bind of didc("didc bind -t dart" )
2. write the dart parsing code according to the javascript.rs and ledger.dart in agent_dart
3. output artifacts in dart code

Here's the input candid file(copy from the candid guide [docs](https://smartcontracts.org/docs/candid-guide/candid-concepts.html))

```
 type address = record {
  street : text;
  city : text;
  zip_code : nat;
  country : text;
};
service address_book : {
  set_address: (name : text, addr : address) -> ();
  get_address: (name : text) -> (opt address) query;
}
```

Here's the artifacts generated by didc demo:
```
class address{
   BigInt zip_code;
   String street;
   String country;
   String city;
  address({ this.zip_code,  this.street,  this.country,  this.city})
  factory adress.fromMap(Map map)({
    return address (
      zip_code:map["zip_code"],
      street:map["street"],
      country:map["country"],
      city:map["city"],
    )
  })
  Map<String,dynamic> toJson()=>{
    return address (
      "zip_code":zip_code,
      "street":street,
      "country":country,
      "city":city,
    )
  }..removeWhere((dynamic key,dynamic value)=> key==null||value==null);
}
Service addressIdl =  IDL.Service({
  'get_address' : IDL.Func([IDL.Text], [IDL.Opt(address)], ['query']),
  'set_address' : IDL.Func([IDL.Text, address], [], []),
});
```

Here's the demo didc and candid file:
[demo.zip](https://github.com/AstroxNetwork/agent_dart/files/7534320/demo.zip)

I'm not quite sure if the artifact meets your requirement, perhaps we could have more discussion based on this demo(including the ETA).

**Comment by neeboo** [comment]
Sorry been taking me a while to look back your demo

I think the major purpose is fitting the criteria, we just need more types def and to build with the real case.

To see if you can generate the Ledger.candid classes and types like we did in wallet/ledger package

So please continue and keep up the good work, if you need any discussion , just ping me.

**Comment by zbyzhlsp** [comment]
hi @neeboo, i've finished most part of the work(still have a little problem,need discuss with you).

This zip file includes the didc full demo, ledger.did and generated dart code:
[demo.zip](https://github.com/AstroxNetwork/agent_dart/files/7778376/demo.zip)

I diffed the output.dart and ledger.dart in agent_dart project,and I think most of the generated code is correct.
But as i mentioned above,there is still a problem not easy to fix:
Check the  definition of AccountIdentifier  in  output.dart and ledger.dart,you'll find it.
I tried  to fix it but failed ,because the  original `candid module`(depended by didc) doesn't provide enough  support to solve it .
May be we can discuss about the detail later when you are free.

**Comment by neeboo** [comment]
> AccountIdentifier

Hi @zbyzhlsp , thanks for the hard work, I have seen you made great progress here.  To complete the whole parser, I think we can try the following paths:

1. For the `AccountDentitfier` , in the Candid, we have `Text`, in agent_dart, we can use primitive types to migrate these types to actual dart classes/types, we shall list all the primitive types, such as Nat64, we use BigInt in agent_dart.

I will update the README in `lib/candid` folder to list the primitive types out.

2. Most of the codes are generated by your modified `didc` however it sometimes does not quite fit the dart-lang specification such as `required` and `;` stuff.  Since we might need lates dart-lang support for generated code. We can use `source_gen` to migrate and reformat the code again, then we can manipulate the `didc` output to compatible with latest dart-lang specification. About this part, I had some experience with `source_gen`, we can work together

**Comment by zbyzhlsp** [comment]
hi @neeboo , I fixed the "AccountDentitfier" like bugs by the approach we discussed yet, and it looks like the output is correct.
About the demo, I added a typedemo.did file besides the ledger.did, to cover the cases of the definition I can come up with.
I pushed the code to the repository I forked from dfinity/candid: https://github.com/zbyzhlsp/candid/tree/dart_bind_support

Here is the compiled demo(including the new added typedemo.did )
[demo3.zip](https://github.com/AstroxNetwork/agent_dart/files/7876835/demo3.zip)

**Comment by neeboo** [comment]
> 

Sorry for replying late. Great work from your last commit. There are some requirements from my side.
Practically, we need `xxx.fromMap()` in factory method and `yyy.toJson()` in toJson() method. But types in fileds are hard to recognized by rust because they are in dart. 

So maybe we can find an alternative way to workaround

**Comment by AlexV525** [comment]
Having an offline chat with @neeboo and @zbyzhlsp, the conclusion is that @zbyzhlsp is OOO and unable to continue with the builder. Unassigning him and assigned myself for further investigations.

**Comment by AlexV525** [comment]
Now we have [candid_dart](https://github.com/AstroxNetwork/candid_dart). Closing as the bounty has been claimed.
