### ISSUE TITLE
Connection refused when fetching status for root key of local replica

### ISSUE THREAD

**Issue by theonlyandreas** [AstroxNetwork/agent_dart#4]
I'm encountering this error when calling fetchRootKey() of HttpAgent in _initAgent():

E/flutter (23155): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: http request failed because SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 46950
E/flutter (23155): #0      HttpAgent._defaultFetch (package:agent_dart/agent/agent/http/index.dart:433:7)
E/flutter (23155): <asynchronous suspension>
E/flutter (23155): #1      HttpAgent.status (package:agent_dart/agent/agent/http/index.dart:362:20)
E/flutter (23155): <asynchronous suspension>
E/flutter (23155): #2      HttpAgent.fetchRootKey (package:agent_dart/agent/agent/http/index.dart:246:20)
E/flutter (23155): <asynchronous suspension>
E/flutter (23155): #3      AgentFactory._initAgent (package:agent_dart_example/init.dart:63:7)
E/flutter (23155): <asynchronous suspension>
E/flutter (23155): 

This means that the port somehow gets changed since I specified port 40161 in the url of the AgentFactory (this is where my local replica runs).
I also tried to directly set the port with the host parameter of HttpAgentOptions but still get the same error.

Am I missing something?

**Comment by neeboo** [comment]
https://github.com/AstroxNetwork/agent_dart/blob/ca5f341b14b0527a0cfa01a5366ff6a6a245f4c3/example/lib/main.dart#L40

Just do it here, like  `http://localhost:40161`

or can you post your code here to see what's going on there

**Comment by theonlyandreas** [comment]
Yes, that's how I did it

I also tried to set the host directly when initializing HttpAgentOptions at 
https://github.com/AstroxNetwork/agent_dart/blob/ca5f341b14b0527a0cfa01a5366ff6a6a245f4c3/example/lib/init.dart#L60 :
like `options: HttpAgentOptions()..identity=_identity..host='localhost:40161',`
but still got the same error..

As far as my setup is concerned, your scripts to build the binaries and link them worked without errors and I'm using an Android Pixel 2 API 29 emulator. (also had to change to $ANDROID_NDK_HOME in variables.sh)

Btw, I found a typo here:
https://github.com/AstroxNetwork/agent_dart/blob/ca5f341b14b0527a0cfa01a5366ff6a6a245f4c3/lib/agent/agent/http/index.dart#L101
This should probably be `defaultPort`

**Comment by neeboo** [comment]
> Yes, that's how I did it
> 
> I also tried to set the host directly when initializing HttpAgentOptions at
> https://github.com/AstroxNetwork/agent_dart/blob/ca5f341b14b0527a0cfa01a5366ff6a6a245f4c3/example/lib/init.dart#L60
> 
> :
> like `options: HttpAgentOptions()..identity=_identity..host='localhost:40161',`
> but still got the same error..
> As far as my setup is concerned, your scripts to build the binaries and link them worked without errors and I'm using an Android Pixel 2 API 29 emulator. (also had to change to $ANDROID_NDK_HOME in variables.sh)
> 
> Btw, I found a typo here:
> https://github.com/AstroxNetwork/agent_dart/blob/ca5f341b14b0527a0cfa01a5366ff6a6a245f4c3/lib/agent/agent/http/index.dart#L101
> 
> 
> This should probably be `defaultPort`

First, thanks for pointing out the typo. will be fixed in next release.

Second, if you use Android emulator , the emulator connects localhost will use "10.0.2.2" instead of "localhost" or "127.0.0.1".

In your case, you should try "http://10.0.2.2:40161" just in the url field

**Comment by theonlyandreas** [comment]
Thanks that was it!
Closing this issue.
