### ISSUE TITLE
Add support for pure dart projects.

### ISSUE THREAD

**Issue by awazgyawali** [AstroxNetwork/agent_dart#47]
Right now the project has a dependency on flutter thus it's not possible to use the package on a pure dart environment like a server-side dart.

Package behaves more like agent_flutter rather than agent_dart.

**Comment by AlexV525** [comment]
Previously we tried to migrate to pure Dart but failed with the current implementation. IMO this will require a federated platform architecture for the plugin. We'll first try to update the plugin in that direction.

**Comment by awazgyawali** [comment]
I needed agent for the flutter web. So I have created a module in my
existing apps code using the federated platform architecture that can pick
agent_dart on mobile platform and use agent_js on web platform to make
query calls to the IC. It's barely working at the moment.

But seeing a pure dart agent_dart would be lovely.

**Comment by neokree** [comment]
@awazgyawali Can you share some code on how you did integrate agent_js on web platform? 
I'm trying to build a starter-kit for Flutter + IC projects

**Comment by awazgyawali** [comment]
> @awazgyawali Can you share some code on how you did integrate agent_js on web platform? I'm trying to build a starter-kit for Flutter + IC projects

CC: @sandeshgyw

**Comment by AlexV525** [comment]
The package `agent_dart_base` is now available for pure Dart projects.
