### ISSUE TITLE
Rejected by IC when using a tuple type as a call parameter

### ISSUE THREAD

**Issue by haida333** [AstroxNetwork/agent_dart#55]
The error is as follows, but the official agent-js will not have this problem.

I/flutter ( 8497): PollingResponseRejectedException
I/flutter ( 8497): Call was rejected:
I/flutter ( 8497):    Request ID: f940e19fa2301477b4e46de087195d03b36105aadc35961feb95a880fb9684d8
I/flutter ( 8497):   Reject code: 
I/flutter ( 8497):    Reject msg: Canister rdmx6-jaaaa-aaaaa-aaadq-cai trapped explicitly: IDL error: did not find tuple field in record

**Comment by neeboo** [comment]
Use candid dart to generate classes and methods
https://github.com/AstroxNetwork/candid_dart

to avoid encode/decode problem
