### ISSUE TITLE
Internet Identity provider url in v1.0.0-dev.17 needs to be updated to https://identity.ic0.app/

### ISSUE THREAD

**Issue by RuBaRuApp** [AstroxNetwork/agent_dart#65]
In agent_dart v1.0.0-dev.17, **'const identityProviderDefault = 'https://identity.icp0.io''** is used in auth_client for Internet Identity login. 

However, this setting causes Internet Identity to throw an error stating '...did not resolve to a canister ID.' I confirmed this by comparing it with the latest versions of **agent-js** and **agent_dart 0.1.24+1**, both of which use **'https://identity.ic0.app/'** and it function as expected. 

See the attached screenshot for reference."

![agent-js](https://github.com/AstroxNetwork/agent_dart/assets/108458290/91cefd59-fd72-4001-aa17-35070bda7c79)
![Error 1](https://github.com/AstroxNetwork/agent_dart/assets/108458290/320bf408-205c-4ae8-a195-d77a72b39c27)
![Error 2](https://github.com/AstroxNetwork/agent_dart/assets/108458290/44e06070-8d09-48d4-889c-912ed16b9d31)

**Comment by AlexV525** [comment]
Thanks for the report. We'll submit the corresponding fix in the next version.
