### ISSUE TITLE
Required named parameter 'parseErrorData' must be provided.

### ISSUE THREAD

**Issue by mwawrusch** [AstroxNetwork/agent_dart#70]
Hi, we upgraded to latest flutter and use magic sdk which depends on agent_dart. We ran into the following issue:

../../../../../.pub-cache/hosted/pub.dev/agent_dart-1.0.0-dev.17/lib/bridge/ffi/ffi_bridge.dart:461:57: Error:
Required named parameter 'parseErrorData' must be provided.
This comes from agent_dart which is referenced in the magic sdk. I tried to pinpoint the agent_dart version and this error shows up for the first time in '1.0.0-dev.15' - Also posted within the magic sdk -> https://github.com/magiclabs/magic-flutter/issues/45

agent_dart is v 1.0.0-dev.17
magic is 4.1.3

[✓] Flutter (Channel stable, 3.13.7, on macOS 13.5.1 22G90 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.83.0)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by AlexV525** [comment]
This is because we haven't upgraded to the latest FRB in our latest released version. We've rolled the version (#69) but got issues when compiling them, still working on it.

**Comment by mwawrusch** [comment]
cool, thx.
