### ISSUE TITLE
ZipFileEncoder.zipDirectory error

### ISSUE THREAD

**Issue by inmarelibero** [AstroxNetwork/agent_dart#75]
After just:
- creating a flutter project
- `flutter pub add agent_dart`
- `flutter pub add agent_dart_auth`
- `flutter pub add file`

I get the following error

```
../../.pub-cache/hosted/pub.dev/agent_dart-0.1.24+1/lib/archiver/encoder.dart:74:8: Error: The method 'SingingBlockZipFileEncoder.zipDirectory' has fewer named arguments than those of overridden method 'ZipFileEncoder.zipDirectory'.
  void zipDirectory(Directory dir,
```

My env:

```
Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 (4 weeks ago) • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1
```

**Comment by AlexV525** [comment]
You have to use the dev version of the package. Sorry for the inconvenience.

**Comment by inmarelibero** [comment]
so this project is not being developed?

**Comment by AlexV525** [comment]
> so this project is not being developed?

No, we just didn't ship a stable version with recent changes.

**Comment by AlexV525** [comment]
The latest version is v1.0.0-dev.22, released 2 months ago.

https://github.com/AstroxNetwork/agent_dart/releases/tag/v1.0.0-dev.22

**Comment by inmarelibero** [comment]
thanks for the clarification

do you have some example with Internet Identity authentication? I can't find any doc nor any examples
