### ISSUE TITLE
How do we report security issues?

### ISSUE THREAD

**Issue by eduarddfinity** [AstroxNetwork/agent_dart#78]
Hi,

My name is Eduard, I work in Dfinity's product security team. During one of our internal reviews we've found some security issues in agent_dart. What would be the best way to share the findings with you? 

Thanks in advance!

**Comment by AlexV525** [comment]
Hi @eduarddfinity. The team should be able to access us directly through Emails, or you can now use the vulnerability report: https://github.com/AstroxNetwork/agent_dart/security/advisories/new

**Comment by eduarddfinity** [comment]
Hi @AlexV525 thanks for the reply. I've just send you an email, we can continue the discussion there!
